In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# Exploratory Data Analysis (EDA) of Pakistan Census Dataset

## 1. Introduction

This project performs exploratory data analysis on a Pakistan census based dataset containing population, demographic, and administrative information across different regions of Pakistan. The dataset includes variables related to population distribution, gender breakdown, urbanization, growth rates, and administrative divisions.

The objective of this analysis is to understand population patterns across provinces, districts, and tehsils and to identify key demographic insights using statistical exploration.



#Dataset Description
Source: Kaggle – Pakistan Census 2017 Dataset
URL: ("https://www.kaggle.com/datasets/usamaraheem/pakistan-census-2017")
Rows: 10,000+
Columns: 17
Time Period: 2017 Census
Collected by: Pakistan Bureau of Statistics (PBS)
Type: Demographic + population statistics
Unit: District/Tehsil level records

## 3. Column Description

- adm_lvl_1 → Province
- adm_lvl_2 → Division
- adm_lvl_3 → District
- adm_lvl_4 → Tehsil/Sub-division
- area_name → Name of area
- area_type → Total / Urban / Rural classification
- area_sq_km → Area in square kilometers
- total_pop → Total population
- total_male → Male population
- total_female → Female population
- total_trans → Transgender population
- sex_ratio → Males per 100 females
- pop_density → Population per sq km
- pct_urban → Percentage urban population
- avg_hh_size → Average household size
- total_pop_98 → Population in 1998
- avg_annual_growth → Annual growth rate

## 4. Data Quality Observations

- The dataset contains missing values in several columns such as area_sq_km, pop_density, and pct_urban due to hierarchical data structure.
- Some variables are only available at aggregated levels (e.g., province totals), while others are missing at rural or urban levels.
- The dataset follows a multi-level administrative structure which results in structured missing data rather than random missingness.

In [3]:
df = pd.read_csv("Pakistan_2017_Census_Final (1).csv")
df.head()

,adm_lvl_1,adm_lvl_2,adm_lvl_3,adm_lvl_4,area_name,area_type,area_sq_km,total_pop,total_male,total_female,total_trans,sex_ratio,pop_density,pct_urban,avg_hh_size,total_pop_98,avg_annual_growth
0,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,TOTAL,347190.0,12335129.0,6483736.0,5850613.0,780.0,110.82,35.53,0.2762,6.87,6565885.0,0.0337
1,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,RURAL,NaN,8928428.0,4685756.0,4242183.0,489.0,110.46,NaN,NaN,6.80,4997105.0,0.0310
2,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,URBAN,NaN,3406701.0,1797980.0,1608430.0,291.0,111.78,NaN,NaN,7.06,1568780.0,0.0416
3,BALOCHISTAN,NaN,AWARAN,NaN,AWARAN DISTRICT,TOTAL,29510.0,121821.0,63063.0,58749.0,9.0,107.34,4.13,0.2810,6.61,118173.0,0.0016
4,BALOCHISTAN,NaN,AWARAN,NaN,AWARAN DISTRICT,RURAL,NaN,87584.0,45438.0,42138.0,8.0,107.83,NaN,NaN,6.25,118173.0,-0.0156

In [11]:
df.shape

(2073, 17)

In [12]:
df.info

<bound method DataFrame.info of         adm_lvl_1 adm_lvl_2 adm_lvl_3           adm_lvl_4           area_name  \
0     BALOCHISTAN       NaN       NaN                 NaN         BALOCHISTAN
1     BALOCHISTAN       NaN       NaN                 NaN         BALOCHISTAN
2     BALOCHISTAN       NaN       NaN                 NaN         BALOCHISTAN
3     BALOCHISTAN       NaN    AWARAN                 NaN     AWARAN DISTRICT
4     BALOCHISTAN       NaN    AWARAN                 NaN     AWARAN DISTRICT
...           ...       ...       ...                 ...                 ...
2068        SINDH       NaN    SUKKUR  SUKKUR CITY TALUKA  SUKKUR CITY TALUKA
2069        SINDH       NaN    SUKKUR  SUKKUR CITY TALUKA  SUKKUR CITY TALUKA
2070    ISLAMABAD       NaN       NaN           ISLAMABAD           ISLAMABAD
2071    ISLAMABAD       NaN       NaN           ISLAMABAD           ISLAMABAD
2072    ISLAMABAD       NaN       NaN           ISLAMABAD           ISLAMABAD

     area_type  area_sq_km   total_pop  total_male  total_female  total_trans  \
0        TOTAL    347190.0  12335129.0   6483736.0     5850613.0        780.0
1        RURAL         NaN   8928428.0   4685756.0     4242183.0        489.0
2        URBAN         NaN   3406701.0   1797980.0     1608430.0        291.0
3        TOTAL     29510.0    121821.0     63063.0       58749.0          9.0
4        RURAL         NaN     87584.0     45438.0       42138.0          8.0
...        ...         ...         ...         ...           ...          ...
2068     RURAL         NaN         NaN         NaN           NaN          NaN
2069     URBAN         NaN    231459.0    118916.0      112511.0         32.0
2070     TOTAL       906.0   2003368.0   1052328.0      950760.0        280.0
2071     RURAL         NaN    994365.0    516723.0      477518.0        124.0
2072     URBAN         NaN   1009003.0    535605.0      473242.0        156.0

      sex_ratio  pop_density  pct_urban  avg_hh_size  total_pop_98  \
0        110.82        35.53     0.2762         6.87     6565885.0
1        110.46          NaN        NaN         6.80     4997105.0
2        111.78          NaN        NaN         7.06     1568780.0
3        107.34         4.13     0.2810         6.61      118173.0
4        107.83          NaN        NaN         6.25      118173.0
...         ...          ...        ...          ...           ...
2068        NaN          NaN        NaN          NaN        2833.0
2069     105.69          NaN        NaN         5.46      212242.0
2070     110.68      2211.22    50.3700         5.86      805235.0
2071     108.21          NaN        NaN         5.94      276055.0
2072     113.18          NaN        NaN         5.78      529180.0

      avg_annual_growth
0                0.0337
1                0.0310
2                0.0416
3                0.0016
4               -0.0156
...                 ...
2068                NaN
2069             0.0046
2070             4.9000
2071             6.9600
2072             3.4500

[2073 rows x 17 columns]>

In [13]:
df.dtypes

adm_lvl_1             object
adm_lvl_2             object
adm_lvl_3             object
adm_lvl_4             object
area_name             object
area_type             object
area_sq_km           float64
total_pop            float64
total_male           float64
total_female         float64
total_trans          float64
sex_ratio            float64
pop_density          float64
pct_urban            float64
avg_hh_size          float64
total_pop_98         float64
avg_annual_growth    float64
dtype: object

In [14]:
df.describe()

,area_sq_km,total_pop,total_male,total_female,total_trans,sex_ratio,pop_density,pct_urban,avg_hh_size,total_pop_98,avg_annual_growth
count,684.000000,1.859000e+03,1.859000e+03,1.859000e+03,1642.000000,1862.00000,682.000000,518.000000,1837.000000,1.835000e+03,1832.000000
mean,3892.381579,8.171552e+05,4.176485e+05,3.994215e+05,96.462850,106.02753,2019.055944,0.408385,6.579777,5.303512e+05,0.029659
std,17126.528751,3.788923e+06,1.931531e+06,1.857251e+06,455.241897,10.27526,8658.409604,2.214225,1.214435,2.527317e+06,0.222095
min,4.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.00000,1.380000,0.000000,0.000000,0.000000e+00,-1.000000
25%,530.500000,7.375800e+04,3.756450e+04,3.545900e+04,7.000000,102.54250,87.525000,0.149100,5.800000,4.712200e+04,0.016900
50%,1212.000000,2.314590e+05,1.189160e+05,1.139360e+05,23.000000,105.70000,340.455000,0.229500,6.310000,1.496150e+05,0.023200
75%,2782.500000,5.646050e+05,2.876630e+05,2.751375e+05,61.000000,108.64750,657.755000,0.362100,7.170000,3.692155e+05,0.030600
max,347190.000000,1.099897e+08,5.590977e+07,5.406745e+07,12435.000000,297.81000,110321.000000,50.370000,12.430000,7.362129e+07,6.960000

In [21]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print("\nColumn:", col)
    print(df[col].value_counts())

Column: adm_lvl_1
adm_lvl_1
PUNJAB         573
SINDH          504
BALOCHISTAN    495
KP             312
FATA           186
ISLAMABAD        3
Name: count, dtype: int64

Column: adm_lvl_2
adm_lvl_2
MALAKAND            99
GUJRANWALA          81
RAWALPINDI          81
SARGODHA            69
FAISALABAD          66
HAZARA              66
LAHORE              66
D.G.KHAN            60
MULTAN              57
BAHAWALPUR          57
KOHAT               33
PESHAWAR            33
SAHIWAL             33
MARDAN              30
DERA ISMAIL KHAN    27
BANNU               21
Name: count, dtype: int64

Column: adm_lvl_3
adm_lvl_3
LASBELA                    30
KHUZDAR                    30
NORTH WAZIRISTAN AGENCY    30
DERA BUGTI                 27
KECH                       27
                           ..
FR D.I.KHAN                 6
FR KOHAT                    6
FR LAKKI MARWAT             6
FR PESHAWAR                 6
NUSHKI                      6
Name: count, Length: 134, dtype: int64

Column: adm_lvl_4
adm_lvl_4
NOWSHERA TEHSIL       6
TAMBOO TEHSIL         6
SAHIWAL TEHSIL        6
MEHRABPUR TALUKA      3
ZEHRI TEHSIL          3
                     ..
PANO AQIL TALUKA      3
ROHRI TALUKA          3
SALEHPAT TALUKA       3
SUKKUR CITY TALUKA    3
MASHKAI TEHSIL        3
Name: count, Length: 533, dtype: int64

Column: area_name
area_name
TAMBOO TEHSIL          6
NOWSHERA TEHSIL        6
SAHIWAL TEHSIL         6
AWARAN TEHSIL          3
GISHKORE SUB-TEHSIL    3
                      ..
PANO AQIL TALUKA       3
ROHRI TALUKA           3
SALEHPAT TALUKA        3
SUKKUR CITY TALUKA     3
ISLAMABAD              3
Name: count, Length: 688, dtype: int64

Column: area_type
area_type
TOTAL    691
RURAL    691
URBAN    691
Name: count, dtype: int64

In [17]:
#missing values 
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2            1194
adm_lvl_3              66
adm_lvl_4             465
area_name               0
area_type               0
area_sq_km           1389
total_pop             214
total_male            214
total_female          214
total_trans           431
sex_ratio             211
pop_density          1391
pct_urban            1555
avg_hh_size           236
total_pop_98          238
avg_annual_growth     241
dtype: int64

In [20]:
#missing percentage 
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent.sort_values(ascending=False)

pct_urban            75.012060
pop_density          67.100820
area_sq_km           67.004342
adm_lvl_2            57.597685
adm_lvl_4            22.431259
total_trans          20.791124
avg_annual_growth    11.625663
total_pop_98         11.480945
avg_hh_size          11.384467
total_female         10.323203
total_pop            10.323203
total_male           10.323203
sex_ratio            10.178485
adm_lvl_3             3.183792
adm_lvl_1             0.000000
area_type             0.000000
area_name             0.000000
dtype: float64

In [22]:
#OUTLIERS
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

area_sq_km: 75 outliers
total_pop: 207 outliers
total_male: 208 outliers
total_female: 209 outliers
total_trans: 192 outliers
sex_ratio: 147 outliers
pop_density: 63 outliers
pct_urban: 55 outliers
avg_hh_size: 74 outliers
total_pop_98: 208 outliers
avg_annual_growth: 145 outliers

In [24]:
#suspisicious data checking 
df.describe(include='all')
for col in num_cols:
    print(col, "negative values:", (df[col] < 0).sum())

area_sq_km negative values: 0
total_pop negative values: 0
total_male negative values: 0
total_female negative values: 0
total_trans negative values: 0
sex_ratio negative values: 0
pop_density negative values: 0
pct_urban negative values: 0
avg_hh_size negative values: 0
total_pop_98 negative values: 0
avg_annual_growth negative values: 64

In [27]:
df.columns

Index(['adm_lvl_1', 'adm_lvl_2', 'adm_lvl_3', 'adm_lvl_4', 'area_name',
       'area_type', 'area_sq_km', 'total_pop', 'total_male', 'total_female',
       'total_trans', 'sex_ratio', 'pop_density', 'pct_urban', 'avg_hh_size',
       'total_pop_98', 'avg_annual_growth'],
      dtype='object')

In [29]:
df_total = df[df["area_type"] == "TOTAL"]

In [31]:
#province highest total population
df.groupby("adm_lvl_1")["total_pop"].sum().sort_values(ascending=False)

adm_lvl_1
PUNJAB         879917240.0
SINDH          287127060.0
KP             244071360.0
BALOCHISTAN     74010774.0
FATA            29958264.0
ISLAMABAD        4006736.0
Name: total_pop, dtype: float64

In [32]:
#district  highest population
result = df[df["adm_lvl_3"].notna()].groupby("adm_lvl_3")["total_pop"].sum().sort_values(ascending=False).head(10)
print(result)

adm_lvl_3
LAHORE            44479940.0
FAISALABAD        31529776.0
RAWALPINDI        21609520.0
GUJRANWALA        20044264.0
RAHIM YAR KHAN    19231048.0
MULTAN            18984664.0
MUZAFFARGARH      17314196.0
PESHAWAR          17068792.0
KARACHI WEST      15628260.0
SIALKOT           15579752.0
Name: total_pop, dtype: float64

In [33]:
print("Total Population of Pakistan:", df_total["total_pop"].sum())

Total Population of Pakistan: 759545717.0

In [34]:
#province highest population density 
result = df_total.groupby("adm_lvl_1")["pop_density"].mean().sort_values(ascending=False)
print(result)

adm_lvl_1
SINDH          6522.743512
ISLAMABAD      2211.220000
PUNJAB          965.731442
KP              671.004592
FATA            251.711290
BALOCHISTAN      86.905590
Name: pop_density, dtype: float64

In [35]:
# male vs female population 
print("Male Population:", df_total["total_male"].sum())
print("Female Population:", df_total["total_female"].sum())

Male Population: 388204259.0
Female Population: 371262262.0

In [36]:
#which area type has highest population 
result = df.groupby("area_type")["total_pop"].sum()
print(result)

area_type
RURAL    488268579.0
TOTAL    759545717.0
URBAN    271277138.0
Name: total_pop, dtype: float64

In [ ]:
Data Quality Report

The dataset used in this analysis is based on Pakistan’s population and administrative census data, containing demographic and geographic information across multiple hierarchical levels, including province, division, district, and tehsil. The dataset includes variables such as total population, gender distribution, area size, population density, urbanization percentage, and population growth indicators.

During exploratory data analysis, several data quality issues were identified. First, missing values were observed in multiple columns, particularly in area_sq_km, pop_density, and pct_urban. These missing values are not random but are structurally present due to the hierarchical nature of the dataset. Certain variables are only available at aggregated administrative levels (such as province totals), while they are not recorded at rural or urban subdivision levels.

Second, the dataset contains multiple administrative levels represented by adm_lvl_1 to adm_lvl_4. This hierarchical structure leads to overlapping records across province, district, and tehsil levels. As a result, care must be taken to avoid duplication when performing aggregated statistical analysis.

Third, variability in population-related variables such as total_pop, total_male, and total_female indicates significant demographic differences across regions. While extreme values exist, these are considered valid and reflect real-world population concentration differences between highly urbanized cities and sparsely populated rural areas.

Additionally, some inconsistencies were observed in derived metrics such as population density and urban percentage, which may result from missing base values or differences in reporting levels.

In Week 2, the planned improvements include handling missing values using appropriate strategies depending on column type and level of aggregation. Duplicate and overlapping records will be carefully managed by filtering based on area_type. Outlier analysis will be further validated to distinguish between genuine extreme values and potential data entry anomalies. Finally, the dataset will be standardized to ensure consistency before performing advanced statistical and visual analysis.